# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tiss\indicatrix_mapper_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Tiss(object):
    def setupUi(self, Tiss):
        Tiss.setObjectName("Tiss")
        Tiss.resize(605, 205)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Tiss.sizePolicy().hasHeightForWidth())
        Tiss.setSizePolicy(sizePolicy)
        Tiss.setMinimumSize(QtCore.QSize(500, 200))
        Tiss.setMaximumSize(QtCore.QSize(1000, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/tiss/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Tiss.setWindowIcon(icon)
        self.btnRun = QtWidgets.QPushButton(Tiss)
        self.btnRun.setGeometry(QtCore.QRect(460, 170, 131, 23))
        self.btnRun.setObjectName("btnRun")
        self.lblLongMin_2 = QtWidgets.QLabel(Tiss)
        self.lblLongMin_2.setGeometry(QtCore.QRect(200, 70, 50, 20))
        self.lblLongMin_2.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_2.setObjectName("lblLongMin_2")
        self.lblLongMin_3 = QtWidgets.QLabel(Tiss)
        self.lblLongMin_3.setGeometry(QtCore.QRect(100, 110, 50, 20))
        self.lblLongMin_3.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_3.setObjectName("lblLongMin_3")
        self.lblLongMin_4 = QtWidgets.QLabel(Tiss)
        self.lblLongMin_4.setGeometry(QtCore.QRect(100, 30, 50, 20))
        self.lblLongMin_4.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_4.setObjectName("lblLongMin_4")
        self.label_14 = QtWidgets.QLabel(Tiss)
        self.label_14.setGeometry(QtCore.QRect(50, 10, 150, 20))
        self.label_14.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.lblCircleSeg_3 = QtWidgets.QLabel(Tiss)
        self.lblCircleSeg_3.setGeometry(QtCore.QRect(430, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCircleSeg_3.sizePolicy().hasHeightForWidth())
        self.lblCircleSeg_3.setSizePolicy(sizePolicy)
        self.lblCircleSeg_3.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCircleSeg_3.setFont(font)
        self.lblCircleSeg_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCircleSeg_3.setObjectName("lblCircleSeg_3")
        self.spbLongMin = QtWidgets.QSpinBox(Tiss)
        self.spbLongMin.setGeometry(QtCore.QRect(50, 70, 50, 20))
        self.spbLongMin.setMinimum(-180)
        self.spbLongMin.setMaximum(180)
        self.spbLongMin.setProperty("value", -150)
        self.spbLongMin.setObjectName("spbLongMin")
        self.spbLongMax = QtWidgets.QSpinBox(Tiss)
        self.spbLongMax.setGeometry(QtCore.QRect(150, 70, 50, 20))
        self.spbLongMax.setMinimum(-180)
        self.spbLongMax.setMaximum(180)
        self.spbLongMax.setProperty("value", 150)
        self.spbLongMax.setObjectName("spbLongMax")
        self.spbLatMax = QtWidgets.QSpinBox(Tiss)
        self.spbLatMax.setGeometry(QtCore.QRect(100, 50, 50, 20))
        self.spbLatMax.setMinimum(-90)
        self.spbLatMax.setMaximum(90)
        self.spbLatMax.setProperty("value", 60)
        self.spbLatMax.setObjectName("spbLatMax")
        self.lblLongMin = QtWidgets.QLabel(Tiss)
        self.lblLongMin.setGeometry(QtCore.QRect(0, 70, 50, 20))
        self.lblLongMin.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin.setObjectName("lblLongMin")
        self.spbLatMin = QtWidgets.QSpinBox(Tiss)
        self.spbLatMin.setGeometry(QtCore.QRect(100, 90, 50, 20))
        self.spbLatMin.setMinimum(-90)
        self.spbLatMin.setMaximum(90)
        self.spbLatMin.setProperty("value", -60)
        self.spbLatMin.setObjectName("spbLatMin")
        self.spbLineSeg = QtWidgets.QSpinBox(Tiss)
        self.spbLineSeg.setGeometry(QtCore.QRect(540, 35, 50, 20))
        self.spbLineSeg.setMinimum(5)
        self.spbLineSeg.setMaximum(200)
        self.spbLineSeg.setProperty("value", 100)
        self.spbLineSeg.setObjectName("spbLineSeg")
        self.label_10 = QtWidgets.QLabel(Tiss)
        self.label_10.setGeometry(QtCore.QRect(290, 10, 100, 20))
        self.label_10.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.lblRadius = QtWidgets.QLabel(Tiss)
        self.lblRadius.setGeometry(QtCore.QRect(285, 30, 110, 20))
        self.lblRadius.setMinimumSize(QtCore.QSize(80, 20))
        self.lblRadius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRadius.setObjectName("lblRadius")
        self.label_6 = QtWidgets.QLabel(Tiss)
        self.label_6.setGeometry(QtCore.QRect(285, 70, 110, 20))
        self.label_6.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lblCircleSeg_2 = QtWidgets.QLabel(Tiss)
        self.lblCircleSeg_2.setGeometry(QtCore.QRect(430, 35, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCircleSeg_2.sizePolicy().hasHeightForWidth())
        self.lblCircleSeg_2.setSizePolicy(sizePolicy)
        self.lblCircleSeg_2.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCircleSeg_2.setFont(font)
        self.lblCircleSeg_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCircleSeg_2.setObjectName("lblCircleSeg_2")
        self.label_11 = QtWidgets.QLabel(Tiss)
        self.label_11.setGeometry(QtCore.QRect(265, 180, 50, 20))
        self.label_11.setMinimumSize(QtCore.QSize(50, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.spbRadiusKm = QtWidgets.QDoubleSpinBox(Tiss)
        self.spbRadiusKm.setGeometry(QtCore.QRect(325, 180, 70, 20))
        self.spbRadiusKm.setDecimals(3)
        self.spbRadiusKm.setMinimum(1.0)
        self.spbRadiusKm.setMaximum(5000.0)
        self.spbRadiusKm.setSingleStep(1.0)
        self.spbRadiusKm.setProperty("value", 667.17)
        self.spbRadiusKm.setObjectName("spbRadiusKm")
        self.label_9 = QtWidgets.QLabel(Tiss)
        self.label_9.setGeometry(QtCore.QRect(271, 149, 50, 20))
        self.label_9.setMinimumSize(QtCore.QSize(50, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.spbRadiusDg = QtWidgets.QDoubleSpinBox(Tiss)
        self.spbRadiusDg.setGeometry(QtCore.QRect(325, 150, 70, 20))
        self.spbRadiusDg.setDecimals(5)
        self.spbRadiusDg.setMinimum(0.0001)
        self.spbRadiusDg.setMaximum(30.0)
        self.spbRadiusDg.setProperty("value", 6.0)
        self.spbRadiusDg.setObjectName("spbRadiusDg")
        self.label_8 = QtWidgets.QLabel(Tiss)
        self.label_8.setGeometry(QtCore.QRect(275, 120, 130, 20))
        self.label_8.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(Tiss)
        self.label_12.setGeometry(QtCore.QRect(405, 75, 66, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.spbCircleSeg = QtWidgets.QSpinBox(Tiss)
        self.spbCircleSeg.setGeometry(QtCore.QRect(540, 10, 40, 20))
        self.spbCircleSeg.setMinimum(5)
        self.spbCircleSeg.setMaximum(100)
        self.spbCircleSeg.setProperty("value", 50)
        self.spbCircleSeg.setObjectName("spbCircleSeg")
        self.chkBoxAux = QtWidgets.QCheckBox(Tiss)
        self.chkBoxAux.setGeometry(QtCore.QRect(460, 145, 130, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkBoxAux.setFont(font)
        self.chkBoxAux.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkBoxAux.setObjectName("chkBoxAux")
        self.label_2 = QtWidgets.QLabel(Tiss)
        self.label_2.setGeometry(QtCore.QRect(115, 70, 20, 20))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/plugins/tiss/graticule.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btnExt = QtWidgets.QPushButton(Tiss)
        self.btnExt.setGeometry(QtCore.QRect(60, 150, 131, 41))
        self.btnExt.setObjectName("btnExt")
        self.spbLatRes = QtWidgets.QDoubleSpinBox(Tiss)
        self.spbLatRes.setGeometry(QtCore.QRect(315, 50, 62, 22))
        self.spbLatRes.setDecimals(5)
        self.spbLatRes.setMinimum(0.0001)
        self.spbLatRes.setMaximum(360.0)
        self.spbLatRes.setProperty("value", 30.0)
        self.spbLatRes.setObjectName("spbLatRes")
        self.spbLongRes = QtWidgets.QDoubleSpinBox(Tiss)
        self.spbLongRes.setGeometry(QtCore.QRect(315, 90, 62, 22))
        self.spbLongRes.setDecimals(5)
        self.spbLongRes.setMinimum(0.0001)
        self.spbLongRes.setMaximum(360.0)
        self.spbLongRes.setProperty("value", 30.0)
        self.spbLongRes.setObjectName("spbLongRes")
        self.label_13 = QtWidgets.QLabel(Tiss)
        self.label_13.setGeometry(QtCore.QRect(410, 105, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.spbSemimajor = QtWidgets.QDoubleSpinBox(Tiss)
        self.spbSemimajor.setGeometry(QtCore.QRect(480, 75, 111, 22))
        self.spbSemimajor.setDecimals(6)
        self.spbSemimajor.setMinimum(1000000.0)
        self.spbSemimajor.setMaximum(10000000.0)
        self.spbSemimajor.setProperty("value", 6378137.0)
        self.spbSemimajor.setObjectName("spbSemimajor")
        self.spbSemiminor = QtWidgets.QDoubleSpinBox(Tiss)
        self.spbSemiminor.setGeometry(QtCore.QRect(480, 105, 111, 22))
        self.spbSemiminor.setDecimals(6)
        self.spbSemiminor.setMinimum(1000000.0)
        self.spbSemiminor.setMaximum(10000000.0)
        self.spbSemiminor.setProperty("value", 6356752.314245)
        self.spbSemiminor.setObjectName("spbSemiminor")

        self.retranslateUi(Tiss)
        QtCore.QMetaObject.connectSlotsByName(Tiss)

    def retranslateUi(self, Tiss):
        _translate = QtCore.QCoreApplication.translate
        Tiss.setWindowTitle(_translate("Tiss", "Indicatrix Mapper"))
        self.btnRun.setText(_translate("Tiss", "Run!"))
        self.lblLongMin_2.setText(_translate("Tiss", "Lon. max"))
        self.lblLongMin_3.setText(_translate("Tiss", "Lat. min"))
        self.lblLongMin_4.setText(_translate("Tiss", "Lat. max"))
        self.label_14.setText(_translate("Tiss", "Extent"))
        self.lblCircleSeg_3.setText(_translate("Tiss", "Cap segments"))
        self.lblLongMin.setText(_translate("Tiss", "Lon. min"))
        self.label_10.setText(_translate("Tiss", "Resolution"))
        self.lblRadius.setText(_translate("Tiss", "Latitude resolution "))
        self.label_6.setText(_translate("Tiss", "Longitude resolution"))
        self.lblCircleSeg_2.setText(_translate("Tiss", "Line segments"))
        self.label_11.setText(_translate("Tiss", "[km] "))
        self.label_9.setText(_translate("Tiss", "[degree] "))
        self.label_8.setText(_translate("Tiss", "Radius of the caps"))
        self.label_12.setText(_translate("Tiss", "a [m]"))
        self.chkBoxAux.setText(_translate("Tiss", "Auxiliary points"))
        self.btnExt.setText(_translate("Tiss", "Use map canvas extent"))
        self.label_13.setText(_translate("Tiss", "b [m]"))

from . import resources_rc